### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by tahpot** [Careview/CareviewApiDemo#2]

**Comment by shearnie** [comment]
Hi Chris,

Currently API documentation is as work in progress and we’re developing the API in relation to requirements for integrations for some other vendors.

Feel free to reach out to me directly : steve.shearn@careviewapp.com<mailto:steve.shearn@careviewapp.com> for any assistance in integrating your system with Careview’s public API.

You’ll need a subscription key provisioned for your integration. And the subscribers of Careview using your integration will need to set up their API keys for their user accounts within Careview itself.

Billing of API consumption is still a work in progress too, so while things are in development you’ll get free access (bonus!) 😊

Let me know what you need, and if you want to progress with a subscription key.

Steve
